config/routes.rb
Rails.application.routes.draw do
  resources :course_assignments
  resources :courses
  resources :professors
  resources :offices
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/course_assignment.rb
class CourseAssignment < ApplicationRecord
  belongs_to :course
  belongs_to :professor
end

app/controllers/course_assignments_controller.rb
class CourseAssignmentsController < ApplicationController
  before_action :set_course_assignment, only: [:show, :edit, :update, :destroy]

  # GET /course_assignments
  # GET /course_assignments.json
  def index
    @course_assignments = CourseAssignment.all
  end

  # GET /course_assignments/1
  # GET /course_assignments/1.json
  def show
  end

  # GET /course_assignments/new
  def new
    @course_assignment = CourseAssignment.new
  end

  # GET /course_assignments/1/edit
  def edit
  end

  # POST /course_assignments
  # POST /course_assignments.json
  def create
    @course_assignment = CourseAssignment.new(course_assignment_params)

    respond_to do |format|
      if @course_assignment.save
        format.html { redirect_to @course_assignment, notice: 'Course assignment was successfully created.' }
        format.json { render :show, status: :created, location: @course_assignment }
      else
        format.html { render :new }
        format.json { render json: @course_assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /course_assignments/1
  # PATCH/PUT /course_assignments/1.json
  def update
    respond_to do |format|
      if @course_assignment.update(course_assignment_params)
        format.html { redirect_to @course_assignment, notice: 'Course assignment was successfully updated.' }
        format.json { render :show, status: :ok, location: @course_assignment }
      else
        format.html { render :edit }
        format.json { render json: @course_assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /course_assignments/1
  # DELETE /course_assignments/1.json
  def destroy
    @course_assignment.destroy
    respond_to do |format|
      format.html { redirect_to course_assignments_url, notice: 'Course assignment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course_assignment
      @course_assignment = CourseAssignment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_assignment_params
      params.require(:course_assignment).permit(:name, :course_id, :professor_id)
    end
end

app/helpers/course_assignments_helper.rb
module CourseAssignmentsHelper
end

app/views/course_assignments/_form.html.erb
<%= form_with(model: course_assignment, local: true) do |form| %>
  <% if course_assignment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course_assignment.errors.count, "error") %> prohibited this course_assignment from being saved:</h2>

      <ul>
        <% course_assignment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">

  </div>

  <div class="field">
    <%= form.label :professor_id %>
    <%= form.collection_select :professor_id,Professor.all ,:id, :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/course_assignments/edit.html.erb
<h1>Editing Course Assignment</h1>

<%= render 'form', course_assignment: @course_assignment %>

<%= link_to 'Show', @course_assignment %> |
<%= link_to 'Back', course_assignments_path %>

app/views/course_assignments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Course Assignments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Course</th>
      <th>Professor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @course_assignments.each do |course_assignment| %>
      <tr>
        <td><%= course_assignment.name %></td>
        <td><%= course_assignment.course_id %></td>
        <td><%= course_assignment.professor_id %></td>
        <td><%= link_to 'Show', course_assignment %></td>
        <td><%= link_to 'Edit', edit_course_assignment_path(course_assignment) %></td>
        <td><%= link_to 'Destroy', course_assignment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course Assignment', new_course_assignment_path %>

app/views/course_assignments/new.html.erb
<h1>New Course Assignment</h1>

<%= render 'form', course_assignment: @course_assignment %>

<%= link_to 'Back', course_assignments_path %>

app/views/course_assignments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @course_assignment.name %>
</p>

<p>
  <strong>Course:</strong>
  <%= @course_assignment.course_id %>
</p>

<p>
  <strong>Professor:</strong>
  <%= @course_assignment.professor_id %>
</p>

<%= link_to 'Edit', edit_course_assignment_path(@course_assignment) %> |
<%= link_to 'Back', course_assignments_path %>